export const EMISSIONUNITS = [
    { id: 1, idLanguage: 1, label: "kgCO2e/kWh net heating" },
    { id: 2, idLanguage: 1, label: "kgCO2e/kWh gross heating" },
    { id: 3, idLanguage: 1, label: "kgCO2e/kWh" },
    { id: 4, idLanguage: 1, label: "kgCO2e/kg" },
    { id: 5, idLanguage: 1, label: "kgCO2e/meal" },
    { id: 6, idLanguage: 1, label: "kgCO2e/tonne.km" },
    { id: 7, idLanguage: 1, label: "kgCO2e/tonne" },
    { id: 8, idLanguage: 1, label: "kgCO2e/km" },
    { id: 9, idLanguage: 1, label: "kgCO2e/passenger.km" },
    { id: 10, idLanguage: 1, label: "kgCO2e/unit" },
    { id: 11, idLanguage: 1, label: "kgCO2e/€ of expense" },
    { id: 12, idLanguage: 1, label: "kgCO2e/L" },
    { id: 13, idLanguage: 1, label: "kgCO2e/m²" },
]
