export const EMISSIONTYPES = [
    { id: 1, id_language: 1, label: "Fuel" },
    { id: 2, id_language: 1, label: "Electricity" },
    { id: 3, id_language: 1, label: "Refrigerant gas" },
    { id: 4, id_language: 1, label: "Principal greenhouse gas" },
    { id: 5, id_language: 1, label: "Meal" },
    { id: 6, id_language: 1, label: "Road haulage" },
    { id: 7, id_language: 1, label: "Air freight" },
    { id: 8, id_language: 1, label: "Freight train" },
    { id: 9, id_language: 1, label: "Cargo ship" },
    { id: 10, id_language: 1, label: "Organic waste" },
    { id: 11, id_language: 1, label: "Other waste" },
    { id: 12, id_language: 1, label: "Transport" },
    { id: 13, id_language: 1, label: "Office equipment" },
    { id: 14, id_language: 1, label: "Electronics and chemical products" },
    { id: 15, id_language: 1, label: "Sports equipment" },
    { id: 16, id_language: 1, label: "Construction" },
    { id: 17, id_language: 1, label: "Equipment" },
]
