export const EMISSIONTYPES = [
    { id: 1, idLanguage: 1, label: "Fuel" },
    { id: 2, idLanguage: 1, label: "Electricity" },
    { id: 3, idLanguage: 1, label: "Refrigerant gas" },
    { id: 4, idLanguage: 1, label: "Principal greenhouse gas" },
    { id: 5, idLanguage: 1, label: "Meal" },
    { id: 6, idLanguage: 1, label: "Road haulage" },
    { id: 7, idLanguage: 1, label: "Air freight" },
    { id: 8, idLanguage: 1, label: "Freight train" },
    { id: 9, idLanguage: 1, label: "Cargo ship" },
    { id: 10, idLanguage: 1, label: "Organic waste" },
    { id: 11, idLanguage: 1, label: "Other waste" },
    { id: 12, idLanguage: 1, label: "Transport" },
    { id: 13, idLanguage: 1, label: "Office equipment" },
    { id: 14, idLanguage: 1, label: "Electronics and chemical products" },
    { id: 15, idLanguage: 1, label: "Sports equipment" },
    { id: 16, idLanguage: 1, label: "Construction" },
    { id: 17, idLanguage: 1, label: "Equipment" },
]
