export const EMISSIONFACTORS = [



  { label: "Delivery truck (authorized loaded weight 19t)", type: "Road haulage", unit: "kgCO2e/tonne.km", value: 0.379, uncertainty: 4 },
  { label: "Local delivery vehicle (authorized loaded weight 7.5t)", type: "Road haulage", unit: "kgCO2e/tonne.km", value: 0.848, uncertainty: 4 },
  { label: "Large volume 26t articulated lorry", type: "Road haulage", unit: "kgCO2e/tonne.km", value: 0.178, uncertainty: 4 },
  { label: "Large volume 40t articulated lorry", type: "Road haulage", unit: "kgCO2e/tonne.km", value: 0.105, uncertainty: 4 },
  { label: "Light utility vehicle", type: "Road haulage", unit: "kgCO2e/tonne.km", value: 1.2, uncertainty: 4 },
  { label: "Air freight – aeroplane > 250 seats, distance travelled 3 000-4 000 km, A1 jet fuel", type: "Air freight", unit: "kgCO2e/tonne.km", value: 2.51, uncertainty: 4 },
  { label: "Freight train (Europe)", type: "Freight train", unit: "kgCO2e/tonne.km", value: 0.0226, uncertainty: 4 },
  { label: "Freight train, electric traction, dense merchandise", type: "Freight train", unit: "kgCO2e/tonne.km", value: 0.00146, uncertainty: 4 },
  { label: "Cargo ship – under 1 200 TEU", type: "Cargo ship", unit: "kgCO2e/tonne.km", value: 0.0331, uncertainty: 4 },
  { label: "Cargo ship – 3 850 to 7 499 TEU", type: "Cargo ship", unit: "kgCO2e/tonne.km", value: 0.0137, uncertainty: 4 },
  { label: "Typical end-of-life treatment", type: "Organic waste", unit: "kgCO2e/tonne", value: 48.1, uncertainty: 5 },
  { label: "Landfill", type: "Organic waste", unit: "kgCO2e/tonne", value: 649, uncertainty: 5 },
  { label: "Incineration", type: "Organic waste", unit: "kgCO2e/tonne", value: 46.6, uncertainty: 5 },
  { label: "Compost (industrial)", type: "Organic waste", unit: "kgCO2e/tonne", value: 86.7, uncertainty: 5 },
  { label: "Paper – typical end of life", type: "Other waste", unit: "kgCO2e/tonne", value: 43.1, uncertainty: 5 },
  { label: "Cardboard – typical end of life", type: "Other waste", unit: "kgCO2e/tonne", value: 37.9, uncertainty: 5 },
  { label: "Glass – typical end of life", type: "Other waste", unit: "kgCO2e/tonne", value: 33, uncertainty: 5 },
  { label: "Plastic – typical end of life", type: "Other waste", unit: "kgCO2e/tonne", value: 877, uncertainty: 5 },
  { label: "Personal car – gasoline/petrol", type: "Transport", unit: "kgCO2e/km", value: 0.259, uncertainty: 2 },
  { label: "Personal car – diesel", type: "Transport", unit: "kgCO2e/km", value: 0.251, uncertainty: 2 },
  { label: "City bus: agglomerations population 100 000 – 250 000", type: "Transport", unit: "kgCO2e/passenger.km", value: 0.146, uncertainty: 5 },
  { label: "City bus: agglomerations population under 100 000", type: "Transport", unit: "kgCO2e/passenger.km", value: 0.137, uncertainty: 5 },
  { label: "City bus: agglomerations population over 250 000", type: "Transport", unit: "kgCO2e/passenger.km", value: 0.129, uncertainty: 5 },
  { label: "Metro", type: "Transport", unit: "kgCO2e/passenger.km", value: 0.006, uncertainty: 2 },
  { label: "Suburban commuter train", type: "Transport", unit: "kgCO2e/passenger.km", value: 0.006, uncertainty: 2 },
  { label: "Tramway", type: "Transport", unit: "kgCO2e/passenger.km", value: 0.006, uncertainty: 2 },
  { label: "Train (average for France)", type: "Transport", unit: "kgCO2e/passenger.km", value: 0.004, uncertainty: 5 },
  { label: "Plane", type: "Transport", unit: "kgCO2e/passenger.km", value: 0.187, uncertainty: 5 },
  { label: "Standard table (furniture)", type: "Office equipment", unit: "kgCO2e/unit", value: 60.100, uncertainty: 2 },
  { label: "Chair (wood)", type: "Office equipment", unit: "kgCO2e/unit", value: 18.600, uncertainty: 1 },
  { label: "Book", type: "Office equipment", unit: "kgCO2e/unit", value: 1.100, uncertainty: 4 },
  { label: "Office supplies and consumables (€)", type: "Office equipment", unit: "kgCO2e/€ of expense", value: 0.917, uncertainty: 1 },
  { label: "Paper (ream)", type: "Office equipment", unit: "kgCO2e/unit", value: 2.290, uncertainty: 2 },
  { label: "AAA batteries (alkaline)", type: "Electronics and chemical products", unit: "kgCO2e/unit", value: 0.065, uncertainty: 4 },
  { label: "AA batteries (alkaline)", type: "Electronics and chemical products", unit: "kgCO2e/unit", value: 0.137, uncertainty: 4 },
  { label: "Hydrochloric acid (litres)", type: "Electronics and chemical products", unit: "kgCO2e/L", value: 1.440, uncertainty: 4 },
  { label: "Sulphuric acid (litres)", type: "Electronics and chemical products", unit: "kgCO2e/L", value: 2.200, uncertainty: 4 },
  { label: "Basketball", type: "Sports equipment", unit: "kgCO2e/unit", value: 4.600, uncertainty: 3 },
  { label: "Soccer ball", type: "Sports equipment", unit: "kgCO2e/unit", value: 4.120, uncertainty: 3 },
  { label: "Volleyball", type: "Sports equipment", unit: "kgCO2e/unit", value: 2.250, uncertainty: 3 },
  { label: "Handball", type: "Sports equipment", unit: "kgCO2e/unit", value: 2.500, uncertainty: 3 },
  { label: "School building (concrete)", type: "Construction", unit: "kgCO2e/m²", value: 440000, uncertainty: 4 },
  { label: "Parking lot (concrete)", type: "Construction", unit: "kgCO2e/m²", value: 319000, uncertainty: 2 },
  { label: "Parking lot (asphalt)", type: "Construction", unit: "kgCO2e/m²", value: 73000, uncertainty: 2 },
  { label: "Parking lot (semi-hard surface)", type: "Construction", unit: "kgCO2e/m²", value: 165000, uncertainty: 2 },
  { label: "Workstation computer", type: "Equipment", unit: "kgCO2e/unit", value: 169000, uncertainty: 4 },
  { label: "Tablets", type: "Equipment", unit: "kgCO2e/unit", value: 63200, uncertainty: 4 },
  { label: "Photocopiers", type: "Equipment", unit: "kgCO2e/unit", value: 2935000, uncertainty: 4 },
  { label: "Video projector", type: "Equipment", unit: "kgCO2e/unit", value: 94000, uncertainty: 5 },
  { label: "Printer", type: "Equipment", unit: "kgCO2e/unit", value: 87900, uncertainty: 4 },
  { label: "Paper – typical end of life", type: "Other waste", unit: "kgCO2e/tonne", value: 43.1, uncertainty: 5 },
  { label: "Cardboard – typical end of life", type: "Other waste", unit: "kgCO2e/tonne", value: 37.9, uncertainty: 5 },
  { label: "Plastic – typical end of life", type: "Other waste", unit: "kgCO2e/tonne", value: 877, uncertainty: 5 },
  { label: "Compost (industrial)", type: "Other waste", unit: "kgCO2e/tonne", value: 86.7, uncertainty: 5 },
  { label: "Typical end-of-life treatment", type: "Other waste", unit: "kgCO2e/tonne", value: 86.7, uncertainty: 5 },
];
