export const EMISSIONFACTORS = [
  { id: 1, id_emission_sub_categorie: 1, id_language: 1, label: "Heating oil", id_type: 1, id_unit: 1, value: 0.324, uncertainty: 0 },
  { id: 2, id_emission_sub_categorie: 1, id_language: 1, label: "Heavy fuel oil", id_type: 1, id_unit: 1, value: 0.324, uncertainty: 0 },
  { id: 3, id_emission_sub_categorie: 1, id_language: 1, label: "Natural gas", id_type: 1, id_unit: 2, value: 0.214, uncertainty: 0 },
  { id: 4, id_emission_sub_categorie: 1, id_language: 1, label: "Wood pellets (8% humidity)", id_type: 1, id_unit: 1, value: 0.0304, uncertainty: 4 },
  { id: 5, id_emission_sub_categorie: 9, id_language: 1, label: "Grid electricity", id_type: 2, id_unit: 3, value: 0.0647, uncertainty: 1 },
  { id: 6, id_emission_sub_categorie: 17, id_language: 1, label: "R134a", id_type: 3, id_unit: 4, value: 1300, uncertainty: 3 },
  { id: 7, id_emission_sub_categorie: 17, id_language: 1, label: "R22 (sales banned since 2015)", id_type: 3, id_unit: 4, value: 1760, uncertainty: 3 },
  { id: 8, id_emission_sub_categorie: 17, id_language: 1, label: "R32", id_type: 3, id_unit: 4, value: 675, uncertainty: 3 },
  { id: 9, id_emission_sub_categorie: 17, id_language: 1, label: "R404a (sales banned since 2020)", id_type: 3, id_unit: 4, value: 3943, uncertainty: 3 },
  { id: 10, id_emission_sub_categorie: 17, id_language: 1, label: "R407c", id_type: 3, id_unit: 4, value: 1624, uncertainty: 3 },
  { id: 11, id_emission_sub_categorie: 17, id_language: 1, label: "R410a", id_type: 3, id_unit: 4, value: 2088, uncertainty: 3 },
  { id: 12, id_emission_sub_categorie: 17, id_language: 1, label: "R452a", id_type: 3, id_unit: 4, value: 2140, uncertainty: 3 },
  { id: 13, id_emission_sub_categorie: 17, id_language: 1, label: "R513a", id_type: 3, id_unit: 4, value: 631, uncertainty: 5 },
  { id: 14, id_emission_sub_categorie: 17, id_language: 1, label: "R744 - CO2", id_type: 3, id_unit: 4, value: 1, uncertainty: 3 },
  { id: 15, id_emission_sub_categorie: 17, id_language: 1, label: "CO2", id_type: 4, id_unit: 4, value: 1, uncertainty: 0 },
  { id: 16, id_emission_sub_categorie: 17, id_language: 1, label: "Fossil CH4", id_type: 4, id_unit: 4, value: 30, uncertainty: 0 },
  { id: 17, id_emission_sub_categorie: 17, id_language: 1, label: "Biogenic CH4", id_type: 4, id_unit: 4, value: 28, uncertainty: 0 },
  { id: 18, id_emission_sub_categorie: 17, id_language: 1, label: "N2O", id_type: 4, id_unit: 4, value: 265, uncertainty: 0 },
  { id: 19, id_emission_sub_categorie: 17, id_language: 1, label: "SF6", id_type: 4, id_unit: 4, value: 23500, uncertainty: 0 },
  { id: 20, id_emission_sub_categorie: 17, id_language: 1, label: "NF3", id_type: 4, id_unit: 4, value: 16100, uncertainty: 0 },
  { id: 21, id_emission_sub_categorie: 5, id_language: 1, label: "Typical meal", id_type: 5, id_unit: 5, value: 2.25, uncertainty: 4 },
  { id: 22, id_emission_sub_categorie: 5, id_language: 1, label: "Vegetarian meal", id_type: 5, id_unit: 5, value: 0.45, uncertainty: 4 },
  { id: 23, id_emission_sub_categorie: 5, id_language: 1, label: "Main course of red meat", id_type: 5, id_unit: 5, value: 7.26, uncertainty: 4 },
  { id: 24, id_emission_sub_categorie: 5, id_language: 1, label: "Main course of white meat", id_type: 5, id_unit: 5, value: 1.58, uncertainty: 4 },
  { id: 25, id_emission_sub_categorie: 6, id_language: 1, label: "Delivery truck (authorized loaded weight 19t)", id_type: 6, id_unit: 6, value: 0.379, uncertainty: 4 },
  { id: 26, id_emission_sub_categorie: 6, id_language: 1, label: "Local delivery vehicle (authorized loaded weight 7.5t)", id_type: 6, id_unit: 6, value: 0.848, uncertainty: 4 },
  { id: 27, id_emission_sub_categorie: 6, id_language: 1, label: "Large volume 26t articulated lorry", id_type: 6, id_unit: 6, value: 0.178, uncertainty: 4 },
  { id: 28, id_emission_sub_categorie: 6, id_language: 1, label: "Large volume 40t articulated lorry", id_type: 6, id_unit: 6, value: 0.105, uncertainty: 4 },
  { id: 29, id_emission_sub_categorie: 6, id_language: 1, label: "Light utility vehicle", id_type: 6, id_unit: 6, value: 1.2, uncertainty: 4 },
  { id: 30, id_emission_sub_categorie: 6, id_language: 1, label: "Air freight – aeroplane > 250 seats, distance travelled 3 000-4 000 km, A1 jet fuel", id_type: 7, id_unit: 6, value: 2.51, uncertainty: 4 },
  { id: 31, id_emission_sub_categorie: 6, id_language: 1, label: "Freight train (Europe)", id_type: 8, id_unit: 6, value: 0.0226, uncertainty: 4 },
  { id: 32, id_emission_sub_categorie: 6, id_language: 1, label: "Freight train, electric traction, dense merchandise", id_type: 8, id_unit: 6, value: 0.00146, uncertainty: 4 },
  { id: 33, id_emission_sub_categorie: 6, id_language: 1, label: "Cargo ship – under 1 200 TEU", id_type: 9, id_unit: 6, value: 0.0331, uncertainty: 4 },
  { id: 34, id_emission_sub_categorie: 6, id_language: 1, label: "Cargo ship – 3 850 to 7 499 TEU", id_type: 9, id_unit: 6, value: 0.0137, uncertainty: 4 },
  { id: 35, id_emission_sub_categorie: 7, id_language: 1, label: "Typical end-of-life treatment", id_type: 10, id_unit: 7, value: 48.1, uncertainty: 5 },
  { id: 36, id_emission_sub_categorie: 7, id_language: 1, label: "Landfill", id_type: 10, id_unit: 7, value: 649, uncertainty: 5 },
  { id: 37, id_emission_sub_categorie: 7, id_language: 1, label: "Incineration", id_type: 10, id_unit: 7, value: 46.6, uncertainty: 5 },
  { id: 38, id_emission_sub_categorie: 7, id_language: 1, label: "Compost (industrial)", id_type: 10, id_unit: 7, value: 86.7, uncertainty: 5 },
  { id: 39, id_emission_sub_categorie: 8, id_language: 1, label: "Paper – typical end of life", id_type: 11, id_unit: 7, value: 43.1, uncertainty: 5 },
  { id: 40, id_emission_sub_categorie: 8, id_language: 1, label: "Cardboard – typical end of life", id_type: 11, id_unit: 7, value: 37.9, uncertainty: 5 },
  { id: 41, id_emission_sub_categorie: 8, id_language: 1, label: "Glass – typical end of life", id_type: 11, id_unit: 7, value: 33, uncertainty: 5 },
  { id: 42, id_emission_sub_categorie: 8, id_language: 1, label: "Plastic – typical end of life", id_type: 11, id_unit: 7, value: 877, uncertainty: 5 },
  { id: 43, id_emission_sub_categorie: 65, id_language: 1, label: "Personal car – gasoline/petrol", id_type: 12, id_unit: 8, value: 0.259, uncertainty: 2 },
  { id: 44, id_emission_sub_categorie: 65, id_language: 1, label: "Personal car – diesel", id_type: 12, id_unit: 8, value: 0.251, uncertainty: 2 },
  { id: 45, id_emission_sub_categorie: 65, id_language: 1, label: "City bus: agglomerations population 100 000 – 250 000", id_type: 12, id_unit: 9, value: 0.146, uncertainty: 5 },
  { id: 46, id_emission_sub_categorie: 65, id_language: 1, label: "City bus: agglomerations population under 100 000", id_type: 12, id_unit: 9, value: 0.137, uncertainty: 5 },
  { id: 47, id_emission_sub_categorie: 65, id_language: 1, label: "City bus: agglomerations population over 250 000", id_type: 12, id_unit: 9, value: 0.129, uncertainty: 5 },
  { id: 48, id_emission_sub_categorie: 65, id_language: 1, label: "Metro", id_type: 12, id_unit: 9, value: 0.006, uncertainty: 2 },
  { id: 49, id_emission_sub_categorie: 65, id_language: 1, label: "Suburban commuter train", id_type: 12, id_unit: 9, value: 0.006, uncertainty: 2 },
  { id: 50, id_emission_sub_categorie: 65, id_language: 1, label: "Tramway", id_type: 12, id_unit: 9, value: 0.006, uncertainty: 2 },
  { id: 51, id_emission_sub_categorie: 65, id_language: 1, label: "Train (average for France)", id_type: 12, id_unit: 9, value: 0.004, uncertainty: 5 },
  { id: 52, id_emission_sub_categorie: 11, id_language: 1, label: "Plane", id_type: 12, id_unit: 9, value: 0.187, uncertainty: 5 },
  { id: 53, id_emission_sub_categorie: 77, id_language: 1, label: "Standard table (furniture)", id_type: 13, id_unit: 10, value: 60.100, uncertainty: 2 },
  { id: 54, id_emission_sub_categorie: 77, id_language: 1, label: "Chair (wood)", id_type: 13, id_unit: 10, value: 18.600, uncertainty: 1 },
  { id: 55, id_emission_sub_categorie: 77, id_language: 1, label: "Book", id_type: 13, id_unit: 10, value: 1.100, uncertainty: 4 },
  { id: 56, id_emission_sub_categorie: 77, id_language: 1, label: "Office supplies and consumables (€)", id_type: 13, id_unit: 11, value: 0.917, uncertainty: 1 },
  { id: 57, id_emission_sub_categorie: 77, id_language: 1, label: "Paper (ream)", id_type: 13, id_unit: 10, value: 2.290, uncertainty: 2 },
  { id: 58, id_emission_sub_categorie: 85, id_language: 1, label: "AAA batteries (alkaline)", id_type: 14, id_unit: 10, value: 0.065, uncertainty: 4 },
  { id: 59, id_emission_sub_categorie: 85, id_language: 1, label: "AA batteries (alkaline)", id_type: 14, id_unit: 10, value: 0.137, uncertainty: 4 },
  { id: 60, id_emission_sub_categorie: 85, id_language: 1, label: "Hydrochloric acid (litres)", id_type: 14, id_unit: 12, value: 1.440, uncertainty: 4 },
  { id: 61, id_emission_sub_categorie: 85, id_language: 1, label: "Sulphuric acid (litres)", id_type: 14, id_unit: 12, value: 2.200, uncertainty: 4 },
  { id: 62, id_emission_sub_categorie: 93, id_language: 1, label: "Basketball", id_type: 15, id_unit: 10, value: 4.600, uncertainty: 3 },
  { id: 63, id_emission_sub_categorie: 93, id_language: 1, label: "Soccer ball", id_type: 15, id_unit: 10, value: 4.120, uncertainty: 3 },
  { id: 64, id_emission_sub_categorie: 93, id_language: 1, label: "Volleyball", id_type: 15, id_unit: 10, value: 2.250, uncertainty: 3 },
  { id: 65, id_emission_sub_categorie: 93, id_language: 1, label: "Handball", id_type: 15, id_unit: 10, value: 2.500, uncertainty: 3 },
  { id: 66, id_emission_sub_categorie: 117, id_language: 1, label: "School building (concrete)", id_type: 16, id_unit: 13, value: 440000, uncertainty: 4 },
  { id: 67, id_emission_sub_categorie: 117, id_language: 1, label: "Parking lot (concrete)", id_type: 16, id_unit: 13, value: 319000, uncertainty: 2 },
  { id: 68, id_emission_sub_categorie: 117, id_language: 1, label: "Parking lot (asphalt)", id_type: 16, id_unit: 13, value: 73000, uncertainty: 2 },
  { id: 69, id_emission_sub_categorie: 117, id_language: 1, label: "Parking lot (semi-hard surface)", id_type: 16, id_unit: 13, value: 165000, uncertainty: 2 },
  { id: 70, id_emission_sub_categorie: 125, id_language: 1, label: "Workstation computer", id_type: 17, id_unit: 10, value: 169000, uncertainty: 4 },
  { id: 71, id_emission_sub_categorie: 125, id_language: 1, label: "Tablets", id_type: 17, id_unit: 10, value: 63200, uncertainty: 4 },
  { id: 72, id_emission_sub_categorie: 125, id_language: 1, label: "Photocopiers", id_type: 17, id_unit: 10, value: 2935000, uncertainty: 4 },
  { id: 73, id_emission_sub_categorie: 125, id_language: 1, label: "Video projector", id_type: 17, id_unit: 10, value: 94000, uncertainty: 5 },
  { id: 74, id_emission_sub_categorie: 125, id_language: 1, label: "Printer", id_type: 17, id_unit: 10, value: 87900, uncertainty: 4 },
];
