export const EMISSIONCATEGORIES = [
  {
    id: 1,
    idLanguage: 1,
    label: 'Energy',
    detail:
      "The energy category focuses on the school's energy consumption over a school year. Initially, data on electricity and heating consumption will be collected. For a complete approach, consumptions linked to chemistry laboratories will also be added.",
    emissionSubCategories: [
      {
        id: 1,
        label: 'Energy - Fuel',
        detail:
          'Your school probably has one or several boilers or furnaces for heating. To operate, these devices may use different types of fossil fuels (fuel oil, natural gas, etc.). The greenhouse gas (GHG) emissions generated by this equipment correspond to the energy consumption of the fuel burned.',
        emissionFactors: [
          { label: 'Heating oil', type: 'Fuel', unit: 'kgCO2e/kWh net heating', value: 0.324, uncertainty: 0 },
          { label: 'Heavy fuel oil', type: 'Fuel', unit: 'kgCO2e/kWh net heating', value: 0.324, uncertainty: 0 },
          { label: 'Natural gas', type: 'Fuel', unit: 'kgCO2e/kWh gross heating', value: 0.214, uncertainty: 0 },
          {
            label: 'Wood pellets (8% humidity)',
            type: 'Fuel',
            unit: 'kgCO2e/kWh net heating',
            value: 0.0304,
            uncertainty: 4,
          },
        ],
      },
      {
        id: 2,

        label: 'Energy - Electricity',
        detail:
          'Your school is connected to the power grid in your country. Electricity is produced in different ways (nuclear power plants, renewable energies, fossil fuel power plants, etc.). Each mode of production emits greenhouse gases (GHGs) in different quantities.',
        emissionFactors: [
          { label: 'Grid electricity', type: 'Electricity', unit: 'kgCO2e/kWh', value: 0.233, uncertainty: 0 },
        ],
      },
      {
        id: 3,

        label: 'Energy - Advanced',
        detail:
          'Your school undoubtedly has science labs equipped with bunsen burners or other equipment that consume energy. There may also be computer servers that consume electricity for storage or other services. These consume energy, contributing to greenhouse gas emissions.',
        emissionFactors: [
          { label: 'R134a', type: 'Refrigerant gas', unit: 'kgCO2e/kg', value: 1300, uncertainty: 3 },
          {
            label: 'R22 (sales banned since 2015)',
            type: 'Refrigerant gas',
            unit: 'kgCO2e/kg',
            value: 1760,
            uncertainty: 3,
          },
          { label: 'R32', type: 'Refrigerant gas', unit: 'kgCO2e/kg', value: 675, uncertainty: 3 },
          {
            label: 'R404a (sales banned since 2020)',
            type: 'Refrigerant gas',
            unit: 'kgCO2e/kg',
            value: 3943,
            uncertainty: 3,
          },
          { label: 'R407c', type: 'Refrigerant gas', unit: 'kgCO2e/kg', value: 1624, uncertainty: 3 },
          { label: 'R410a', type: 'Refrigerant gas', unit: 'kgCO2e/kg', value: 2088, uncertainty: 3 },
          { label: 'R452a', type: 'Refrigerant gas', unit: 'kgCO2e/kg', value: 2140, uncertainty: 3 },
          { label: 'R513a', type: 'Refrigerant gas', unit: 'kgCO2e/kg', value: 631, uncertainty: 5 },
          { label: 'R744 - CO2', type: 'Refrigerant gas', unit: 'kgCO2e/kg', value: 1, uncertainty: 3 },
          { label: 'CO2', type: 'Principal greenhouse gas', unit: 'kgCO2e/kg', value: 1, uncertainty: 0 },
          { label: 'Fossil CH4', type: 'Principal greenhouse gas', unit: 'kgCO2e/kg', value: 30, uncertainty: 0 },
          { label: 'Biogenic CH4', type: 'Principal greenhouse gas', unit: 'kgCO2e/kg', value: 28, uncertainty: 0 },
          { label: 'N2O', type: 'Principal greenhouse gas', unit: 'kgCO2e/kg', value: 265, uncertainty: 0 },
          { label: 'SF6', type: 'Principal greenhouse gas', unit: 'kgCO2e/kg', value: 23500, uncertainty: 0 },
          { label: 'NF3', type: 'Principal greenhouse gas', unit: 'kgCO2e/kg', value: 16100, uncertainty: 0 },
        ],
      },
    ],
  },
  {
    id: 2,
    idLanguage: 1,
    label: 'Food Service',
    detail:
      'In the Food service category, students must calculate emissions linked to meals served. In certain schools, data on food sold in canteens and vending machines will also be collected.',
    emissionSubCategories: [
      {
        id: 4,
        label: 'Food - Basic 1',
        detail:
          'Here you will calculate emissions related to meals served in your school lunchroom, canteen or self-service cafeteria. Be sure you calculate the total number of meals for the entire year! We suggest you use the period January through December.Number of meals provided by the school divided into options. If your schools is not providing a food service you can still count the lunches you consume during the school year. In this way you’ll be able to compare your data at European level!',
        emissionFactors: [
          { label: 'Typical meal', type: 'Meal', unit: 'kgCO2e/meal', value: 2.25, uncertainty: 4 },
          { label: 'Vegetarian meal', type: 'Meal', unit: 'kgCO2e/meal', value: 0.45, uncertainty: 4 },
          { label: 'Main course of red meat', type: 'Meal', unit: 'kgCO2e/meal', value: 7.26, uncertainty: 4 },
          { label: 'Main course of white meat', type: 'Meal', unit: 'kgCO2e/meal', value: 1.58, uncertainty: 4 },
        ],
      },
      {
        id: 5,
        label: 'Food - Basic 2',
        detail:
          'Here you will calculate emissions related to the food available in food dispensers. Be sure you calculate the total number of food purchased for the entire year! We suggest you use the period January through December.If your school does not have food dispensers, fill this part with 0.',
        emissionFactors: [
          { label: 'Typical meal', type: 'Meal', unit: 'kgCO2e/meal', value: 2.25, uncertainty: 4 },
          { label: 'Vegetarian meal', type: 'Meal', unit: 'kgCO2e/meal', value: 0.45, uncertainty: 4 },
          { label: 'Main course of red meat', type: 'Meal', unit: 'kgCO2e/meal', value: 7.26, uncertainty: 4 },
          { label: 'Main course of white meat', type: 'Meal', unit: 'kgCO2e/meal', value: 1.58, uncertainty: 4 },
        ],
      },
      {
        id: 6,
        label: 'Food - Delivery',
        detail:
          'Your school probably has a lunchroom, canteen or self-service cafeteria. All the food that you eat there is brought in by various means of transport, which have emitted greenhouse gases. Record here the vehicles used to deliver food supplies to the canteen or cafeteria. Cover the whole year if you can! Pay attention to the units requested). Suppliers of food in your school, how do they deliver the food to the schools and for how many km do they travel.',
        emissionFactors: [
          {
            label: 'Delivery truck (authorized loaded weight 19t)',
            type: 'Road haulage',
            unit: 'kgCO2e/tonne.km',
            value: 0.379,
            uncertainty: 4,
          },
          {
            label: 'Local delivery vehicle (authorized loaded weight 7.5t)',
            type: 'Road haulage',
            unit: 'kgCO2e/tonne.km',
            value: 0.848,
            uncertainty: 4,
          },
          {
            label: 'Large volume 26t articulated lorry',
            type: 'Road haulage',
            unit: 'kgCO2e/tonne.km',
            value: 0.178,
            uncertainty: 4,
          },
          {
            label: 'Large volume 40t articulated lorry',
            type: 'Road haulage',
            unit: 'kgCO2e/tonne.km',
            value: 0.105,
            uncertainty: 4,
          },
          { label: 'Light utility vehicle', type: 'Road haulage', unit: 'kgCO2e/tonne.km', value: 1.2, uncertainty: 4 },
          {
            label: 'Air freight – aeroplane > 250 seats, distance travelled 3 000-4 000 km, A1 jet fuel',
            type: 'Air freight',
            unit: 'kgCO2e/tonne.km',
            value: 2.51,
            uncertainty: 4,
          },
          {
            label: 'Freight train (Europe)',
            type: 'Freight train',
            unit: 'kgCO2e/tonne.km',
            value: 0.0226,
            uncertainty: 4,
          },
          {
            label: 'Freight train, electric traction, dense merchandise',
            type: 'Freight train',
            unit: 'kgCO2e/tonne.km',
            value: 0.00146,
            uncertainty: 4,
          },
          {
            label: 'Cargo ship – under 1 200 TEU',
            type: 'Cargo ship',
            unit: 'kgCO2e/tonne.km',
            value: 0.0331,
            uncertainty: 4,
          },
          {
            label: 'Cargo ship – 3 850 to 7 499 TEU',
            type: 'Cargo ship',
            unit: 'kgCO2e/tonne.km',
            value: 0.0137,
            uncertainty: 4,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    idLanguage: 1,
    label: 'Travel',
    detail:
      'The Travel category focuses on emissions linked to home-establishment travel of students, teachers, and non-teaching staff, as well as school trips if any take place.',
    emissionSubCategories: [
      {
        id: 7,
        label: 'Transport - School Buses',
        detail:
          'The use of school buses for student transportation contributes to greenhouse gas emissions. Efficient route planning, vehicle maintenance, and the use of low-emission vehicles can help reduce these emissions.',
        emissionFactors: [
          {
            label: 'City bus: agglomerations population 100 000 – 250 000',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.146,
            uncertainty: 5,
          },
          {
            label: 'City bus: agglomerations population under 100 000',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.137,
            uncertainty: 5,
          },
          {
            label: 'City bus: agglomerations population over 250 000',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.129,
            uncertainty: 5,
          },
        ],
      },
      {
        id: 8,
        label: 'Transport - Staff Vehicles',
        detail:
          'The vehicles used by school staff for commuting or other school-related activities also contribute to greenhouse gas emissions. Carpooling, use of public transport, or transitioning to electric vehicles can mitigate these emissions.',
        emissionFactors: [
          {
            label: 'Personal car – gasoline/petrol',
            type: 'Transport',
            unit: 'kgCO2e/km',
            value: 0.259,
            uncertainty: 2,
          },
          { label: 'Personal car – diesel', type: 'Transport', unit: 'kgCO2e/km', value: 0.251, uncertainty: 2 },
          {
            label: 'City bus: agglomerations population 100 000 – 250 000',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.146,
            uncertainty: 5,
          },
          {
            label: 'City bus: agglomerations population under 100 000',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.137,
            uncertainty: 5,
          },
          {
            label: 'City bus: agglomerations population over 250 000',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.129,
            uncertainty: 5,
          },
          { label: 'Metro', type: 'Transport', unit: 'kgCO2e/passenger.km', value: 0.006, uncertainty: 2 },
          {
            label: 'Suburban commuter train',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.006,
            uncertainty: 2,
          },
          { label: 'Tramway', type: 'Transport', unit: 'kgCO2e/passenger.km', value: 0.006, uncertainty: 2 },
          {
            label: 'Train (average for France)',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.004,
            uncertainty: 5,
          },
          { label: 'Plane', type: 'Transport', unit: 'kgCO2e/passenger.km', value: 0.187, uncertainty: 5 },
        ],
      },
      {
        id: 9,
        label: 'Travel - Personnel',
        detail:
          'To go a bit farther, it would be interesting to record travel by school staff as well. As for students, a questionnaire is a good way to start collecting data for each type of travel. Work with the surveys to estimate: total amount of km (round trip) and in which percentage the different means of transportation are used by the personnel.',
        emissionFactors: [
          {
            label: 'Personal car – gasoline/petrol',
            type: 'Transport',
            unit: 'kgCO2e/km',
            value: 0.259,
            uncertainty: 2,
          },
          { label: 'Personal car – diesel', type: 'Transport', unit: 'kgCO2e/km', value: 0.251, uncertainty: 2 },
          {
            label: 'City bus: agglomerations population 100 000 – 250 000',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.146,
            uncertainty: 5,
          },
          {
            label: 'City bus: agglomerations population under 100 000',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.137,
            uncertainty: 5,
          },
          {
            label: 'City bus: agglomerations population over 250 000',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.129,
            uncertainty: 5,
          },
          { label: 'Metro', type: 'Transport', unit: 'kgCO2e/passenger.km', value: 0.006, uncertainty: 2 },
          {
            label: 'Suburban commuter train',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.006,
            uncertainty: 2,
          },
          { label: 'Tramway', type: 'Transport', unit: 'kgCO2e/passenger.km', value: 0.006, uncertainty: 2 },
          {
            label: 'Train (average for France)',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.004,
            uncertainty: 5,
          },
          { label: 'Plane', type: 'Transport', unit: 'kgCO2e/passenger.km', value: 0.187, uncertainty: 5 },
        ],
      },
      {
        id: 10,
        label: 'Travel - School Trips',
        detail:
          'If your school organizes field trips this travel should be counted as well. Add up the distance travelled and multiply by the number of persons who take the trip. Work with the surveys to estimate: the ratio between the number of passengers and the total amount of km (round trip) used by school trips.',
        emissionFactors: [
          {
            label: 'Personal car – gasoline/petrol',
            type: 'Transport',
            unit: 'kgCO2e/km',
            value: 0.259,
            uncertainty: 2,
          },
          { label: 'Personal car – diesel', type: 'Transport', unit: 'kgCO2e/km', value: 0.251, uncertainty: 2 },
          {
            label: 'City bus: agglomerations population 100 000 – 250 000',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.146,
            uncertainty: 5,
          },
          {
            label: 'City bus: agglomerations population under 100 000',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.137,
            uncertainty: 5,
          },
          {
            label: 'City bus: agglomerations population over 250 000',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.129,
            uncertainty: 5,
          },
          { label: 'Metro', type: 'Transport', unit: 'kgCO2e/passenger.km', value: 0.006, uncertainty: 2 },
          {
            label: 'Suburban commuter train',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.006,
            uncertainty: 2,
          },
          { label: 'Tramway', type: 'Transport', unit: 'kgCO2e/passenger.km', value: 0.006, uncertainty: 2 },
          {
            label: 'Train (average for France)',
            type: 'Transport',
            unit: 'kgCO2e/passenger.km',
            value: 0.004,
            uncertainty: 5,
          },
          { label: 'Plane', type: 'Transport', unit: 'kgCO2e/passenger.km', value: 0.187, uncertainty: 5 },
        ],
      },
    ],
  },
  {
    id: 4,
    idLanguage: 1,
    label: 'Supplies',
    detail:
      'In the Supplies category, all the material bought for the school year is entered. These are mostly consumables or short-life products that will be used during the year and will have to be bought again next year.',
    emissionSubCategories: [
      {
        id: 11,
        label: 'Supplies - Furnitures And Supplies',
        detail:
          'Your middle school or high school buys equipment and furniture so that classes can be held and students can learn in good conditions. Here you will estimate the GHG emissions linked to the purchase of supplies other than foodstuffs (food purchases are reported in the Food service tab). Count the totality of the items purchased by the school during the school year and insert the data.',
        emissionFactors: [
          {
            label: 'Standard table (furniture)',
            type: 'Office equipment',
            unit: 'kgCO2e/unit',
            value: 60.1,
            uncertainty: 2,
          },
          { label: 'Chair (wood)', type: 'Office equipment', unit: 'kgCO2e/unit', value: 18.6, uncertainty: 1 },
          { label: 'Book', type: 'Office equipment', unit: 'kgCO2e/unit', value: 1.1, uncertainty: 4 },
          {
            label: 'Office supplies and consumables (€)',
            type: 'Office equipment',
            unit: 'kgCO2e/€ of expense',
            value: 0.917,
            uncertainty: 1,
          },
          { label: 'Paper (ream)', type: 'Office equipment', unit: 'kgCO2e/unit', value: 2.29, uncertainty: 2 },
        ],
      },
      {
        id: 12,
        label: 'Supplies - Chemical Supplies For Electronic',
        detail:
          'Think about the materials you use in science and technology classes and labs. These products emit greenhouse gases which should be counted. You can find the quantities of materials purchased each year by consulting the invoices paid by the school. Count the totality of the items in the school and insert the data.',
        emissionFactors: [
          {
            label: 'AAA batteries (alkaline)',
            type: 'Electronics and chemical products',
            unit: 'kgCO2e/unit',
            value: 0.065,
            uncertainty: 4,
          },
          {
            label: 'AA batteries (alkaline)',
            type: 'Electronics and chemical products',
            unit: 'kgCO2e/unit',
            value: 0.137,
            uncertainty: 4,
          },
          {
            label: 'Hydrochloric acid (litres)',
            type: 'Electronics and chemical products',
            unit: 'kgCO2e/L',
            value: 1.44,
            uncertainty: 4,
          },
          {
            label: 'Sulphuric acid (litres)',
            type: 'Electronics and chemical products',
            unit: 'kgCO2e/L',
            value: 2.2,
            uncertainty: 4,
          },
        ],
      },
      {
        id: 13,
        label: 'Supplies - Sports Equipment',
        detail:
          'Equipment is also used in physical education, and has to be replaced sometimes. Here you can report purchases of new equipment bought during the year of your inventory. Count the totality of the items in the school and insert the data.',
        emissionFactors: [
          { label: 'Basketball', type: 'Sports equipment', unit: 'kgCO2e/unit', value: 4.6, uncertainty: 3 },
          { label: 'Soccer ball', type: 'Sports equipment', unit: 'kgCO2e/unit', value: 4.12, uncertainty: 3 },
          { label: 'Volleyball', type: 'Sports equipment', unit: 'kgCO2e/unit', value: 2.25, uncertainty: 3 },
          { label: 'Handball', type: 'Sports equipment', unit: 'kgCO2e/unit', value: 2.5, uncertainty: 3 },
        ],
      },
    ],
  },
  {
    id: 5,
    idLanguage: 1,
    label: 'Fixed Assets',
    detail:
      'The Fixed assets category covers buildings/renovations and goods classified as "long-term" such as IT equipment, production machinery, etc. The emissions generated by the manufacture of these goods are spread over a conventionally chosen period (20 years for buildings, 5 years for IT equipment).',
    emissionSubCategories: [
      {
        id: 14,
        label: 'Fixed Assets - Building',
        detail:
          "All construction involves greenhouse gas emissions. What are the emissions of your school building or buildings? Even if the school was built long ago, it is what is known as a 'fixed asset'. To account for the building's life span, the construction emissions are spread out over the years (depreciation). Insert the number of m2 of the building of your school and of its parking lots (they can be of different kinds!).",
        emissionFactors: [
          {
            label: 'School building (concrete)',
            type: 'Construction',
            unit: 'kgCO2e/m²',
            value: 440000,
            uncertainty: 4,
          },
          { label: 'Parking lot (concrete)', type: 'Construction', unit: 'kgCO2e/m²', value: 319000, uncertainty: 2 },
          { label: 'Parking lot (asphalt)', type: 'Construction', unit: 'kgCO2e/m²', value: 73000, uncertainty: 2 },
          {
            label: 'Parking lot (semi-hard surface)',
            type: 'Construction',
            unit: 'kgCO2e/m²',
            value: 165000,
            uncertainty: 2,
          },
        ],
      },
      {
        id: 15,
        label: 'Fixed Assets - IT Equipment',
        detail:
          'Do you remember our discussion of the environmental impact of smartphones? Likewise, raw materials are used to make computers and IT equipment. These are also fixed assets. The same accounting method is used to spread out the emissions over the life of the equipment (depreciation). Count the totality of the items in the school and insert the data.',
        emissionFactors: [
          { label: 'Workstation computer', type: 'Equipment', unit: 'kgCO2e/unit', value: 169000, uncertainty: 4 },
          { label: 'Tablets', type: 'Equipment', unit: 'kgCO2e/unit', value: 63200, uncertainty: 4 },
          { label: 'Photocopiers', type: 'Equipment', unit: 'kgCO2e/unit', value: 2935000, uncertainty: 4 },
          { label: 'Video projector', type: 'Equipment', unit: 'kgCO2e/unit', value: 94000, uncertainty: 5 },
          { label: 'Printer', type: 'Equipment', unit: 'kgCO2e/unit', value: 87900, uncertainty: 4 },
        ],
      },
    ],
  },
]
