export const EMISSIONCATEGORIES = [
    {
        id: 1,
        idLanguage: 1,
        label: 'Energy',
        detail:
            "The energy category focuses on the school's energy consumption over a school year. Initially, data on electricity and heating consumption will be collected. For a complete approach, consumptions linked to chemistry laboratories will also be added.",
        emissionSubCategories: [
            {
                label: 'Energy - Fuel',
                detail:
                    'Your school probably has one or several boilers or furnaces for heating. To operate, these devices may use different types of fossil fuels (fuel oil, natural gas, etc.). The greenhouse gas (GHG) emissions generated by this equipment correspond to the energy consumption of the fuel burned.',
                emissionFactors: [
                    { label: 'Heating oil', type: 'Fuel', unit: 'kgCO2e/kWh net heating', value: 0.324, uncertainty: 0 },
                    { label: 'Heavy fuel oil', type: 'Fuel', unit: 'kgCO2e/kWh net heating', value: 0.324, uncertainty: 0 },
                    { label: 'Natural gas', type: 'Fuel', unit: 'kgCO2e/kWh gross heating', value: 0.214, uncertainty: 0 },
                    {
                        label: 'Wood pellets (8% humidity)',
                        type: 'Fuel',
                        unit: 'kgCO2e/kWh net heating',
                        value: 0.0304,
                        uncertainty: 4,
                    },
                ],
            },
            {
                label: 'Energy - Electricity',
                detail:
                    'Your school is connected to the power grid in your country. Electricity is produced in different ways (nuclear power plants, renewable energies, fossil fuel power plants, etc.). Each mode of production emits greenhouse gases (GHGs) in different quantities.',
                emissionFactors: [
                    { label: 'Grid electricity', type: 'Electricity', unit: 'kgCO2e/kWh', value: 0.233, uncertainty: 0 },
                ],
            },
            {
                label: 'Energy - Advanced',
                detail:
                    'Your school undoubtedly has science labs equipped with bunsen burners or other equipment that consume energy. There may also be computer servers that consume electricity for storage or other services. These consume energy, contributing to greenhouse gas emissions.',
                emissionFactors: [
                    { label: 'R134a', type: 'Refrigerant gas', unit: 'kgCO2e/kg', value: 1300, uncertainty: 3 },
                    {
                        label: 'R22 (sales banned since 2015)',
                        type: 'Refrigerant gas',
                        unit: 'kgCO2e/kg',
                        value: 1760,
                        uncertainty: 3,
                    },
                    { label: 'R32', type: 'Refrigerant gas', unit: 'kgCO2e/kg', value: 675, uncertainty: 3 },
                    {
                        label: 'R404a (sales banned since 2020)',
                        type: 'Refrigerant gas',
                        unit: 'kgCO2e/kg',
                        value: 3943,
                        uncertainty: 3,
                    },
                    { label: 'R407c', type: 'Refrigerant gas', unit: 'kgCO2e/kg', value: 1624, uncertainty: 3 },
                    { label: 'R410a', type: 'Refrigerant gas', unit: 'kgCO2e/kg', value: 2088, uncertainty: 3 },
                    { label: 'R452a', type: 'Refrigerant gas', unit: 'kgCO2e/kg', value: 2140, uncertainty: 3 },
                    { label: 'R513a', type: 'Refrigerant gas', unit: 'kgCO2e/kg', value: 631, uncertainty: 5 },
                    { label: 'R744 - CO2', type: 'Refrigerant gas', unit: 'kgCO2e/kg', value: 1, uncertainty: 3 },
                    { label: 'CO2', type: 'Principal greenhouse gas', unit: 'kgCO2e/kg', value: 1, uncertainty: 0 },
                    { label: 'Fossil CH4', type: 'Principal greenhouse gas', unit: 'kgCO2e/kg', value: 30, uncertainty: 0 },
                    { label: 'Biogenic CH4', type: 'Principal greenhouse gas', unit: 'kgCO2e/kg', value: 28, uncertainty: 0 },
                    { label: 'N2O', type: 'Principal greenhouse gas', unit: 'kgCO2e/kg', value: 265, uncertainty: 0 },
                    { label: 'SF6', type: 'Principal greenhouse gas', unit: 'kgCO2e/kg', value: 23500, uncertainty: 0 },
                    { label: 'NF3', type: 'Principal greenhouse gas', unit: 'kgCO2e/kg', value: 16100, uncertainty: 0 },
                ],
            },
        ],
    },
    {
        id: 9,
        idLanguage: 1,
        label: 'Food Service',
        detail:
            'In the Food service category, students must calculate emissions linked to meals served. In certain schools, data on food sold in canteens and vending machines will also be collected.',
        emissionSubCategories: [
            {
                label: 'Food - Basic 1',
                detail:
                    'Here you will calculate emissions related to meals served in your school lunchroom, canteen or self-service cafeteria. Be sure you calculate the total number of meals for the entire year! We suggest you use the period January through December.Number of meals provided by the school divided into options. If your schools is not providing a food service you can still count the lunches you consume during the school year. In this way you’ll be able to compare your data at European level!',
                emissionFactors: [
                    { label: 'Typical meal', type: 'Meal', unit: 'kgCO2e/meal', value: 2.25, uncertainty: 4 },
                    { label: 'Vegetarian meal', type: 'Meal', unit: 'kgCO2e/meal', value: 0.45, uncertainty: 4 },
                    { label: 'Main course of red meat', type: 'Meal', unit: 'kgCO2e/meal', value: 7.26, uncertainty: 4 },
                    { label: 'Main course of white meat', type: 'Meal', unit: 'kgCO2e/meal', value: 1.58, uncertainty: 4 },
                ],
            },
            {
                label: 'Food - Basic 2',
                detail:
                    'Here you will calculate emissions related to the food available in food dispensers. Be sure you calculate the total number of food purchased for the entire year! We suggest you use the period January through December.If your school does not have food dispensers, fill this part with 0.',
                emissionFactors: [
                    { label: 'Typical meal', type: 'Meal', unit: 'kgCO2e/meal', value: 2.25, uncertainty: 4 },
                    { label: 'Vegetarian meal', type: 'Meal', unit: 'kgCO2e/meal', value: 0.45, uncertainty: 4 },
                    { label: 'Main course of red meat', type: 'Meal', unit: 'kgCO2e/meal', value: 7.26, uncertainty: 4 },
                    { label: 'Main course of white meat', type: 'Meal', unit: 'kgCO2e/meal', value: 1.58, uncertainty: 4 },
                ],

            },
            {
                label: 'Food - Delivery',
                detail:
                    'Your school probably has a lunchroom, canteen or self-service cafeteria. All the food that you eat there is brought in by various means of transport, which have emitted greenhouse gases. Record here the vehicles used to deliver food supplies to the canteen or cafeteria. Cover the whole year if you can! Pay attention to the units requested). Suppliers of food in your school, how do they deliver the food to the schools and for how many km do they travel.',

            },
        ],
    },
    {
        id: 17,
        idLanguage: 1,
        label: 'Travel',
        detail:
            'The Travel category focuses on emissions linked to home-establishment travel of students, teachers, and non-teaching staff, as well as school trips if any take place.',
    },
    {
        id: 25,
        idLanguage: 1,
        label: 'Supplies',
        detail:
            'In the Supplies category, all the material bought for the school year is entered. These are mostly consumables or short-life products that will be used during the year and will have to be bought again next year.',
    },
    {
        id: 33,
        idLanguage: 1,
        label: 'Fixed Assets',
        detail:
            'The Fixed assets category covers buildings/renovations and goods classified as "long-term" such as IT equipment, production machinery, etc. The emissions generated by the manufacture of these goods are spread over a conventionally chosen period (20 years for buildings, 5 years for IT equipment).',
    },
]
