
DROP TABLE SESSION_EMISSIONS;
DROP TABLE COMMENTS;
DROP TABLE EMISSION_FACTORS;
DROP TABLE EMISSION_SUB_CATEGORIES;
DROP TABLE SESSION_EMISSION_CATEGORIES;
DROP TABLE EMISSION_CATEGORIES;
DROP TABLE SESSION_STUDENTS;
DROP TABLE GROUPS;
DROP TABLE SCHOOLS;
DROP TABLE EMISSION_UNITS;
DROP TABLE EMISSION_TYPES;
DROP TABLE LANGUAGES;

CREATE TABLE LANGUAGES (
    id INT PRIMARY KEY,
    language_code CHAR(2) NOT NULL
);
CREATE TABLE EMISSION_TYPES (
    id INT PRIMARY KEY,
    id_language INT REFERENCES LANGUAGES(id),
    label VARCHAR(255) NOT NULL
);
CREATE TABLE EMISSION_UNITS (
    id INT PRIMARY KEY,
    id_language INT REFERENCES LANGUAGES(id),
    label VARCHAR(255) NOT NULL
);
CREATE TABLE SCHOOLS (
    id BIGSERIAL PRIMARY KEY,
    state TEXT NOT NULL,
    name TEXT NOT NULL,
    town_name TEXT NOT NULL,
    postal_code TEXT NOT NULL,
    student_count INTEGER,
    staff_count INTEGER,
    establishment_year INTEGER,
    adress TEXT NOT NULL,
    admin_username TEXT NOT NULL
);
CREATE TABLE GROUPS (
    id BIGSERIAL PRIMARY KEY,
    id_school INT REFERENCES SCHOOLS(id),
    teacher_username VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    year INT,
    archived BOOLEAN DEFAULT false,
    deleted BOOLEAN DEFAULT false
);
CREATE TABLE SESSION_STUDENTS (
    id BIGSERIAL PRIMARY KEY,
    id_school INT REFERENCES SCHOOLS(id),
    id_group INT,
    name VARCHAR(255) NOT NULL,
    year INT,
    progression INT DEFAULT 0,
    archived BOOLEAN DEFAULT false,
    deleted BOOLEAN DEFAULT false
);
CREATE TABLE EMISSION_CATEGORIES (
    id INT PRIMARY KEY,
    id_emission_categorie INT REFERENCES EMISSION_CATEGORIES(id),
    id_language INT REFERENCES LANGUAGES(id),
    label VARCHAR(255) NOT NULL,
    detail VARCHAR(2550) NOT NULL
);
CREATE TABLE SESSION_EMISSION_CATEGORIES (
    id BIGSERIAL PRIMARY KEY,
    id_student_session INT REFERENCES SESSION_STUDENTS(id),
    id_emission_categorie INT REFERENCES EMISSION_CATEGORIES(id)
);
CREATE TABLE EMISSION_SUB_CATEGORIES (
    id INT PRIMARY KEY,
    id_emission_categorie INT REFERENCES EMISSION_CATEGORIES(id),
    id_language INT REFERENCES LANGUAGES(id),
    label VARCHAR(255) NOT NULL,
    detail VARCHAR(2550) NOT NULL
);
CREATE TABLE SESSION_EMISSION_SUB_CATEGORIES (
    id BIGSERIAL PRIMARY KEY,
    id_emission_sub_categorie INT REFERENCES EMISSION_SUB_CATEGORIES(id)
);
CREATE TABLE EMISSION_FACTORS (
    id INT PRIMARY KEY,
    id_emission_sub_categorie INT REFERENCES EMISSION_SUB_CATEGORIES(id),
    id_language INT REFERENCES LANGUAGES(id),
    label VARCHAR(255) NOT NULL,
    id_type INT REFERENCES EMISSION_TYPES(id),
    id_unit INT REFERENCES EMISSION_UNITS(id),
    value NUMERIC,
    uncertainty NUMERIC
);
CREATE TABLE COMMENTS (
    id INT PRIMARY KEY,
    id_emission_sub_categorie INT REFERENCES SESSION_EMISSION_SUB_CATEGORIES(id),
    comment TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_created_by INT
);
CREATE TABLE SESSION_EMISSIONS (
    id BIGSERIAL PRIMARY KEY,
    id_session_emission_sub_categorie INT REFERENCES SESSION_EMISSION_SUB_CATEGORIES(id),
    id_emission_factor INT REFERENCES EMISSION_FACTORS(id),
    value NUMERIC
);